###
GET http://localhost:9393

### Deliveries
### Query to get all deliveries
GET http://localhost:9393/deliveries

### Query to get deliveries by id
GET http://localhost:9393/deliveries/2

### Query to add delivery
POST http://localhost:9393/adddelivery
Content-Type: application/json

{
    "id": "1",
    "creation_date": "2022-07-13",
    "state": "pending",
    "pickup_lat": 1,
    "pickup_lon": 2,
    "dropoff_lat": 1,
    "dropoff_lon": 2,
    "zone_id": "zone2"
}

### Query to update delivery state
PATCH http://localhost:9393/changestatedelivery
Content-Type: application/json

{
    "id": "1",
    "newState": "assigned"
}


### Bots
### Query to get all bots
GET http://localhost:9393/bots

### Query to get bots by id
GET http://localhost:9393/bots/3

### Query to add bot
POST http://localhost:9393/addbot
Content-Type: application/json

{
    "id": "6",
    "status": "available",
    "dropoff_lat": 1,
    "dropoff_lon": 2,
    "zone_id": "zone1"
}

### Query to update bots status
PATCH http://localhost:9393/changebotstatus
Content-Type: application/json

{
    "id": "5",
    "newStatus": "reserved"
}