###
GET http://localhost:9393

### Deliveries
### Query to get all deliveries
GET http://localhost:9393/deliveries

### Query to add delivery
POST http://localhost:9393/adddelivery
Content-Type: application/json

{
    "id": "third",
    "creation_date": "2022-07-12",
    "state": "pending"
}

### Query to update delivery state
PATCH http://localhost:9393/changestate
Content-Type: application/json

{
    "id": "second",
    "creation_date": "2022-07-12",
    "newState": "free"
}