###
GET http://localhost:9393

###
GET http://localhost:9393/robots

### Get robot by id
GET http://localhost:9393/robots/1

### Get robot by status
GET http://localhost:9393/robots/available

### Create robot
POST http://localhost:9393/addrobot
Content-Type: application/json

{
    "id": 6,
    "name": "Robot 6",
    "status": "available"
}